const yaml = require('js-yaml');

// No version number in the header, deliberately: it would go stale in every
// diff of a committed config and tell the reader nothing they cannot get from
// the repo. The pointer to the reference is the useful half.
// Added by Claude Code (claude-opus-5[1m])
const HEADER = [
    '# Generated by baker init. Edit freely.',
    '# Reference: docs/baker-yml-reference.md'
];

// Pure: an answers object in, a config string out. No filesystem, no prompts.
//
// Built as a plain object and handed to js-yaml rather than assembled from
// string concatenation. That is what makes AC-2 true by construction — a
// retired key (vm:, vagrant:, container:, persistent:) cannot appear unless
// something here puts it there — and it means quoting is the serialiser's
// problem, so an environment name containing ':' or '#' round-trips instead of
// producing a file that will not parse.
// Added by Claude Code (claude-opus-5[1m])
function render(answers) {
    // Validated here rather than trusted from the prompts, because js-yaml's
    // failure for a missing value is `unacceptable kind of an object to dump
    // [object Undefined]`, which names neither the field nor the caller.
    if (typeof answers.name !== 'string' || !answers.name.trim()) {
        throw new Error('An environment name is required.');
    }

    const doc = { name: answers.name };

    Object.assign(doc, targetKey(answers));

    const tools = toolsSection(answers);
    if (tools) doc.tools = tools;

    const packages = (answers.packages || []).filter(Boolean);
    if (packages.length) doc.packages = packages;

    const config = configSection(answers);
    if (config) doc.config = config;

    // lineWidth: -1 disables js-yaml's line folding. A folded long value is
    // still valid YAML, but an instructor opening the file to edit a path
    // should not find it wrapped across lines.
    const body = yaml.safeDump(doc, { lineWidth: -1, noRefs: true });

    return `${HEADER.join('\n')}\n${body}`;
}

// The one key that binds a decision for people not in the room: chooseProvider
// reads it from the committed file and there is no student-side override today.
function targetKey(answers) {
    if (answers.target === 'docker') {
        return { docker: answers.image || 'ubuntu:latest' };
    }

    if (answers.target === 'remote') {
        // All three fields are required, and this refuses rather than emitting a
        // stub. Nothing downstream will catch it: chooseProvider calls
        // RemoteProvider.validateBakerYML WITHOUT awaiting it, and the function
        // is async — so it always returns a truthy promise and the check never
        // fails. A partial remote: block would reach a real bake unremarked.
        const missing = [
            ['user', answers.user],
            ['ip', answers.ip],
            ['private_key', answers.privateKey]
        ].filter(([, value]) => !String(value || '').trim()).map(([field]) => field);

        if (missing.length) {
            throw new Error(
                `remote: needs ${missing.join(', ')}. ` +
                `All of user, ip, and private_key are required.`
            );
        }

        return {
            remote: {
                user: answers.user,
                ip: answers.ip,
                private_key: answers.privateKey
            }
        };
    }

    if (answers.target === 'local') {
        // `local: .` — the environment root is the directory holding baker.yml,
        // which is the repo the instructor is authoring in and the student clones.
        return { local: '.' };
    }

    // Explicit rather than defaulting to local. A fourth target added later
    // without updating this function would otherwise emit a silent `local: .`
    // and the instructor would ship a config that provisions the wrong place.
    throw new Error(
        `Unknown target '${answers.target}'. Expected one of: local, docker, remote.`
    );
}

// A tools: entry is a bare name, or a mapping when the bakelet requires a field.
// pip and npm take a list; baker and docker-extension take a single string.
const TAKES_LIST = ['pip', 'npm'];

function toolsSection(answers) {
    const tools = answers.tools || [];
    if (!tools.length) return null;

    return tools.map((name) => {
        const arg = (answers.toolArgs || {})[name];
        if (!arg) return name;

        if (TAKES_LIST.includes(name)) {
            return { [name]: { packages: splitList(arg) } };
        }
        return { [name]: arg };
    });
}

// The per-unit material students receive. `prune: true` is what makes a re-bake
// for the next unit REPLACE what the last one placed rather than accumulate
// both — the convergence requirement that makes this safe to re-run.
//
// Note the shape: `prune` is a sibling of `files`, not a member of the list.
function configSection(answers) {
    if (!answers.materials) return null;

    const entry = {
        files: [{ src: answers.materials, dest: '.' }]
    };
    if (answers.prune) entry.prune = true;

    return [entry];
}

// A blank or absent answer is an empty list, not a list containing the word
// "undefined" — which is what String(undefined) would otherwise hand to a
// package manager.
function splitList(value) {
    if (value === undefined || value === null) return [];

    return String(value)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
}

module.exports = { render, splitList, HEADER };
